queue_rules:
- name: default
  conditions:
  - status-success=test

pull_request_rules:
- name: request review on external contributor
  conditions:
  - -author=PurpleBooth
  actions:
    assign:
      add_users:
      - PurpleBooth

- name: automatic merge for Dependabot pull requests
  conditions:
  - author~=^dependabot(|-preview)\[bot\]$
  - status-success=test
  actions:
    queue:
      method: rebase
      rebase_fallback: merge
      name: default
