options:
  prev_tag: versio-prev

projects:
- name: alfred-emoji-snippet-pack
  id: 1
  tag_prefix: ''
  labels: tag
  version:
    tags:
      default: 0.1.0

sizes:
  use_angular: true
  none: [ci]
