name: Build GitHub Releases
on:
  push:
    tags-ignore:
    - versio-prev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        lfs: true
    - uses: nick-invision/retry@v2.4.0
      with:
        timeout_minutes: 10
        max_attempts: 5
        command: sudo apt-get update && sudo apt-get install -y bats
    - uses: ruby/setup-ruby@v1
    - run: |
        bundle config set path 'vendor/bundle'
        bundle install
        make clean build test
    - uses: actions/upload-artifact@v2
      with:
        name: alfredsnippet-pack
        path: ./build/Emoji.alfredsnippets
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      name: Checkout the repository
      with:
        lfs: true
        fetch-depth: 0
    - id: get_previous_version
      name: Get the previous version
      run: echo ::set-output name=PREVIOUS_VERSION::$(git tag | sort --version-sort
        | tail -n 3 | head -n 1)
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - uses: actions/download-artifact@v2
    - uses: dlavrenuek/conventional-changelog-action@v1.1.1
      name: Generate change log
      id: changelog
      with:
        from: ${{ steps.get_previous_version.outputs.PREVIOUS_VERSION }}
        to: ${{ steps.get_version.outputs.VERSION }}
    - env:
        GITHUB_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
      id: create_release
      name: Create GitHub Release
      uses: actions/create-release@v1.1.4
      with:
        draft: false
        prerelease: false
        body: ${{ steps.changelog.outputs.body }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        tag_name: ${{ steps.get_version.outputs.VERSION }}
    - uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./alfredsnippet-pack/Emoji.alfredsnippets
        asset_name: Emoji.alfredsnippets
        asset_content_type: application/zip
