'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          lfs: true
      - uses: nick-invision/retry@v1.0.4
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: sudo apt-get update && sudo apt-get install -y bats
      - uses: masa-iwasaki/setup-rbenv@1.2.0
      - run: |
          eval "$(rbenv init -)"
          rbenv install -s $(cat .ruby-version)
          bundle config set path 'vendor/bundle'
          bundle install
          make clean build test
      - uses: actions/upload-artifact@v2
        with:
          name: alfredsnippet-pack
          path: ./build/Emoji.alfredsnippets
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - uses: actions/download-artifact@v2
      - id: create_release
        uses: actions/create-release@v1.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./alfredsnippet-pack/Emoji.alfredsnippets
          asset_name: Emoji.alfredsnippets
          asset_content_type: application/zip
