name: Pipeline
on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  versio-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: chaaz/versio-actions/install@v1.2
        name: Install versio
      - name: Check projects
        run: versio check
      - name: Print changes
        run: versio plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
      - name: version bump details
        run: versio release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: nick-invision/retry@v2.7.0
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: sudo apt-get update && sudo apt-get install -y bats
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: ruby/setup-ruby@v1
      - uses: PurpleBooth/gfmfmt-action@v2.0.7
        name: Check markdown is well formatted
      - run: |
          bundle config set path 'vendor/bundle'
          bundle install
          make clean build test
      - uses: actions/upload-artifact@v3
        with:
          name: alfredsnippet-pack
          path: ./build/Emoji.alfredsnippets
  release:
    if: github.ref == 'refs/heads/main'
    needs:
      - versio-plan
      - test
    outputs:
      version_bump: ${{ steps.version_bump.outputs.version_bump }}
      current_version: ${{ steps.current_version.outputs.current_version }}
      previous_version: ${{ steps.previous_version.outputs.previous_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: chaaz/versio-actions/install@v1.2
        name: Install versio
      - id: previous_version
        run: echo ::set-output "name=previous_version::$( versio get --id 1 -v )"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
      - run: echo ::set-output "name=BUMP::$( versio release --dry-run )"
        id: get_versio_plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}

      - name: Generate release
        if: ${{ contains(steps.get_versio_plan.outputs.BUMP, ' -> ') }}
        run: |
          versio release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
          RUST_LOG: versio=trace
          RUST_BACKTRACE: 1
      - run: echo ::set-output "name=current_version::$( versio get --id 1 -v )"
        id: current_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
      - run: echo ::set-output "name=version_bump::true"
        if: steps.current_version.outputs.current_version != steps.previous_version.outputs.previous_version
        id: version_bump

  upload-release:
    if: needs.release.outputs.version_bump
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the repository
        with:
          lfs: true
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        with:
          config: cliff.toml
          args: --verbose --latest
        env:
          OUTPUT: CHANGELOG.md
      - uses: actions/download-artifact@v3
        name: Download package to be released
      - name: Generate Hashes
        run: sha256sum Emoji.alfredsnippets > SHA256SUMS
        working-directory: alfredsnippet-pack
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          token: ${{ github.token }}
          bodyFile: "CHANGELOG.md"
          name: Release v${{ needs.release.outputs.current_version }}
          tag: v${{ needs.release.outputs.current_version }}
          artifacts: "./alfredsnippet-pack/Emoji.alfredsnippets*,SHA256SUMS"
