on:
  push:
    branches:
      - master

name: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - uses: masa-iwasaki/setup-rbenv@v1
      - run: |
          eval "$(rbenv init -)"
          rbenv install -s $(cat .ruby-version)
          bundle install --path vendor/bundle
          make clean build test
      - uses: actions/upload-artifact@master
        with:
          name: alfredsnippet-pack
          path: ./build/Emoji.alfredsnippets
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-output "name=action_build_date::$(date +%Y%m%d%H%M%S%N)"
        id: build_date
      - uses: actions/download-artifact@master
        with:
          name: alfredsnippet-pack
      - id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.1.${{ steps.build_date.outputs.action_build_date }}
          release_name: Release v0.1.${{ steps.build_date.outputs.action_build_date }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./alfredsnippet-pack/Emoji.alfredsnippets
          asset_name: Emoji.alfredsnippets
          asset_content_type: application/zip