name: Test
on:
  push:
    branches:
    - '*'
  pull_request:
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: chaaz/versio-actions/install@v1.1
      name: Install versio
    - name: Check projects
      run: versio check
    - name: Print changes
      run: versio plan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.actor }}
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        command: sudo apt-get update && sudo apt-get install -y bats
    - uses: actions/checkout@v2.3.4
      with:
        lfs: true
    - uses: ruby/setup-ruby@v1
    - run: |
        bundle config set path 'vendor/bundle'
        bundle install
        make clean build test
    - uses: actions/upload-artifact@v2
      with:
        name: alfredsnippet-pack
        path: ./build/Emoji.alfredsnippets
