on:
  push: ~
  schedule:
    - cron:  '0 8 * * *'

name: Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: sudo apt-get update && sudo apt-get install -y bats
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: masa-iwasaki/setup-rbenv@v1
      - run: |
          eval "$(rbenv init -)"
          rbenv install -s $(cat .ruby-version)
          bundle install --path vendor/bundle
          make clean build test
      - uses: actions/upload-artifact@v2
        with:
          name: alfredsnippet-pack
          path: ./build/Emoji.alfredsnippets
