on:
  push: ~
  schedule:
    - cron:  '0 8 * * *'

name: Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y bats
      - uses: actions/checkout@master
        with:
          lfs: true
      - uses: masa-iwasaki/setup-rbenv@v1
      - run: |
          eval "$(rbenv init -)"
          rbenv install -s $(cat .ruby-version)
          bundle install --path vendor/bundle
          make clean build test
      - uses: actions/upload-artifact@master
        with:
          name: alfredsnippet-pack
          path: ./build/Emoji.alfredsnippets